name: washouse_staff
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_svg: ^1.0.3
  page_transition: ^2.0.9
  flutter_otp_text_field: ^1.1.1
  animated_bottom_navigation_bar: ^1.1.0+1
  flutter_rating_bar: ^4.0.1
  flutter_barcode_scanner: ^2.0.0
  flutter_osm_plugin: ^0.53.1
  google_sign_in: ^6.0.2
  flutter_otp: ^0.3.2
  anim_search_bar: ^2.0.3
  skeletons: ^0.0.3
  shared_preferences: 
  percent_indicator: ^4.2.3
  otp_text_field: ^1.1.3
  image_picker: ^0.8.7+1
  flutter_datetime_picker: ^1.5.1
  flutter_cupertino_localizations: ^1.0.1
  dotted_line: ^3.1.0
  intl: ^0.17.0-nullsafety.2
  rive: ^0.10.3
  flutter_speed_dial: ^6.2.0
  qr_code_scanner: ^1.0.1
  flutter_switch: ^0.3.2
  flutter_form_builder: ^7.8.0
  timelines: ^0.1.0
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  cloud_firestore: ^4.5.1
  firebase_storage: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/washouse-favicon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/
    - assets/images/avatar/
    - assets/images/empty/
    - assets/images/logo/
    - assets/images/order/
    - assets/images/payments/
    - assets/images/resetpwd/
    - assets/images/shipping/
    - assets/images/started/